import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dashboard from "./dashboard/Dashboard";

import { Box } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DataPoint</title>
        <meta name="description" content="Generated by DataPoint" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ display: "flex", flexDirection: "row" }}>
          <Dashboard />
        </Box>
      </main>
    </div>
  );
};

export default Home;
